# Generated by Django 5.2 on 2025-05-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
